output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value = module.eks.kubeconfig
}

output "region" {
  description = "AWS region"
  value = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value = local.cluster_name
}

output "docker_registry_url" {
  value = aws_ecr_repository.sw_kubernetes_repo.repository_url
}

output "docker_registry_id" {
  value = aws_ecr_repository.sw_kubernetes_repo.registry_id
}
