package:
  name: h2o_pysparkling_scoring_SUBST_SPARK_MAJOR_VERSION
  version: SUBST_SW_VERSION

source:
  path: ../../pkg

requirements:
  build:
    - python
    - pip >=9.0.1
    - setuptools

  run:
    - python

about:
  home: https://github.com/h2oai/sparkling-water.git
  license: Apache License Version 2.0
  license_family: Apache
