aws_region	    				= "us-east-1"
aws_access_key 					= "ACCESS_KEY"
aws_secret_key 					= "SECRET_KEY"
aws_subnet_id					= "subnet-29781070"
aws_vpc_id						= "vpc-33878256"
aws_security_group_master_id	= "sg-b536d6cd"
aws_security_group_slave_id		= "sg-b636d6ce"

aws_core_instance_count = "3"
aws_instance_type		= "m3.xlarge"
sw_major_version		= "2.3"
sw_patch_version		= "14"
