{% set data >= load_setup_py_data() %}

package:
  name: h2o
  version: {{ data.get("version") }}

source:
  path: ../..

requirements:
  build:
    - python
    - pip >=9.0.1
    - setuptools
    - colorama >=0.3.7
    - future >=0.15.2
    - tabulate >=0.7.5
    - requests >=2.10
    - six
    - pyspark >= 2.4.0

  run:
    - python
    - colorama >=0.3.7
    - future >=0.15.2
    - tabulate >=0.7.5
    - requests >=2.10
    - six
    - pyspark >= 2.4.0

  test:
    - pip >= 9.0.3
    - colorama >= 0.3.9
    - future >= 0.16.0
    - requests >= 2.18.4
    - tabulate >= 0.8.2
    - six
    - pyspark >= 2.4.0

about:
  home: https://github.com/h2oai/sparkling-water.git
  license: Apache License Version 2.0
  license_family: Apache

