package:
  name: h2o_pysparkling_SUBST_SPARK_MAJOR_VERSION
  version: SUBST_SW_VERSION

source:
  path: ../../pkg

requirements:
  build:
    - python
    - pip >=9.0.1
    - setuptools
    - future >=0.15.2
    - tabulate >=0.7.5
    - requests >=2.10

  run:
    - python
    - future >=0.15.2
    - tabulate >=0.7.5
    - requests >=2.10

about:
  home: https://github.com/h2oai/sparkling-water.git
  license: GNU Affero General Public License v3
  license_family: AGPL
